
spring:  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gameplans?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ehdruakim12@
  
  jpa:
    # true 설정시 JPA 쿼리문 확인 가능
    show-sql: true
    hibernate:
      # JPA의 구현체인 Hibernate가 동작하면서 발생한 SQL의 가독성을 높여준다.
      format_sql: true
      ddl-auto: update
      
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  devtools:
    livereload:
      enabled: true # 정적 리소스에 변화가 있을 때 바로 반영한다.

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
                
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false    # thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
    check-template-location: true   # templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킨다.

